# Generated by Django 5.2.1 on 2025-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_orderd',
            field=models.BooleanField(default=False),
        ),
    ]
