# Generated by Django 5.2.1 on 2025-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='Image/default_profile.png', null=True, upload_to='Image'),
        ),
    ]
